### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by OleksandrPopovych** [cihologramas/pyueye#11]
I faced a lot of errors during installation:
```
ueye/ueyeh.c:12456:36: error: ‘IS_GET_CAMERA_LUT_USER’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_GET_CAMERA_LUT_USER); if (unlikely(!__pyx
                                    ^
ueye/ueyeh.c:12456:36: note: each undeclared identifier is reported only once for each function it appears in
ueye/ueyeh.c:13332:36: error: ‘IS_SET_CAMERA_LUT_VALUES’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_SET_CAMERA_LUT_VALUES); if (unlikely(!__p
                                    ^
ueye/ueyeh.c:13404:36: error: ‘IS_CAMERA_LUT_64’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_CAMERA_LUT_64); if (unlikely(!__pyx_t_1))
                                    ^
ueye/ueyeh.c:13584:36: error: ‘IS_GET_CAMERA_LUT_SUPPORTED_CHANNELS’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_GET_CAMERA_LUT_SUPPORTED_CHANNELS); if (u
                                    ^
ueye/ueyeh.c:15192:36: error: ‘IS_CAMERA_LUT_MAP1’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_CAMERA_LUT_MAP1); if (unlikely(!__pyx_t_1
                                    ^
ueye/ueyeh.c:18624:36: error: ‘IS_CAMERA_LUT_COLD_HOT’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_CAMERA_LUT_COLD_HOT); if (unlikely(!__pyx
                                    ^
ueye/ueyeh.c:18816:36: error: ‘IS_CAMERA_LUT_GLOW2’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_CAMERA_LUT_GLOW2); if (unlikely(!__pyx_t_
                                    ^
ueye/ueyeh.c:18828:36: error: ‘IS_CAMERA_LUT_GLOW1’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_CAMERA_LUT_GLOW1); if (unlikely(!__pyx_t_
                                    ^
ueye/ueyeh.c:19176:36: error: ‘IS_CAMERA_LUT_ONLY_BLUE’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_CAMERA_LUT_ONLY_BLUE); if (unlikely(!__py
                                    ^
ueye/ueyeh.c:19428:36: error: ‘IS_GET_CAMERA_LUT_COMPLETE’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_GET_CAMERA_LUT_COMPLETE); if (unlikely(!_
                                    ^
ueye/ueyeh.c:19848:36: error: ‘IS_CAMERA_LUT_ONLY_RED’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_CAMERA_LUT_ONLY_RED); if (unlikely(!__pyx
                                    ^
ueye/ueyeh.c:20232:36: error: ‘IS_GET_GAMMA’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_GET_GAMMA); if (unlikely(!__pyx_t_1)) __P
                                    ^
ueye/ueyeh.c:21180:36: error: ‘IS_ENABLE_RGB_GRAYSCALE’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_ENABLE_RGB_GRAYSCALE); if (unlikely(!__py
                                    ^
ueye/ueyeh.c:21372:36: error: ‘IS_CAMERA_LUT_128’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_CAMERA_LUT_128); if (unlikely(!__pyx_t_1)
                                    ^
ueye/ueyeh.c:21408:36: error: ‘IS_DEFAULT_GAMMA’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_DEFAULT_GAMMA); if (unlikely(!__pyx_t_1))
                                    ^
ueye/ueyeh.c:22308:36: error: ‘IS_SENSOR_UIF005_C’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_SENSOR_UIF005_C); if (unlikely(!__pyx_t_1
                                    ^
ueye/ueyeh.c:22344:36: error: ‘IS_SENSOR_UIF005_M’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_SENSOR_UIF005_M); if (unlikely(!__pyx_t_1
                                    ^
ueye/ueyeh.c:23496:36: error: ‘IS_MIN_GAMMA’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_MIN_GAMMA); if (unlikely(!__pyx_t_1)) __P
                                    ^
ueye/ueyeh.c:24084:36: error: ‘IS_CAMERA_LUT_RAINBOW1’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_CAMERA_LUT_RAINBOW1); if (unlikely(!__pyx
                                    ^
ueye/ueyeh.c:25080:36: error: ‘IS_CAMERA_LUT_NEGATIV’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_CAMERA_LUT_NEGATIV); if (unlikely(!__pyx_
                                    ^
ueye/ueyeh.c:26808:36: error: ‘IS_MAX_GAMMA’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_MAX_GAMMA); if (unlikely(!__pyx_t_1)) __P
                                    ^
ueye/ueyeh.c:27360:36: error: ‘IS_ENABLE_CAMERA_LUT’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_ENABLE_CAMERA_LUT); if (unlikely(!__pyx_t
                                    ^
ueye/ueyeh.c:29352:36: error: ‘IS_CAMERA_LUT_IDENTITY’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_CAMERA_LUT_IDENTITY); if (unlikely(!__pyx
                                    ^
ueye/ueyeh.c:29904:36: error: ‘IS_CAMERA_LUT_SEPIC’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_CAMERA_LUT_SEPIC); if (unlikely(!__pyx_t_
                                    ^
ueye/ueyeh.c:30024:36: error: ‘IS_CAMERA_LUT_ASTRO1’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_CAMERA_LUT_ASTRO1); if (unlikely(!__pyx_t
                                    ^
ueye/ueyeh.c:30804:36: error: ‘IS_CAMERA_LUT_ONLY_GREEN’ undeclared (first use in this function)
   __pyx_t_1 = __Pyx_PyInt_From_int(IS_CAMERA_LUT_ONLY_GREEN); if (unlikely(!__p
                                    ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
How to resolve this?

**Comment by ramezquitao** [comment]
What version of the UEYE driver are you using, and what branch of pyueye
are you using?


Ricardo Amézquita Orozco
Doctor en Ciencias - Física
Director de Investigación y Desarrollo

CI Hologramas - Combustión Ingenieros S.A.S.
Cll 25B # 85B - 76, Bogotá / Colombia
Tel: 57-1-2635232
Fax: 57-1-4296516
http://www.cihologramas.com

On Tue, Oct 17, 2017 at 7:26 AM, OleksandrPopovych <notifications@github.com

**Comment by OleksandrPopovych** [comment]
Driver: uEye-Linux-4.82.02-64-bit
pyueye: 4.82.2.0

**Comment by ramezquitao** [comment]
I just compiled the pyueye (branch 4.82), in a debian 9 system with the ueye 4.82.13 drivers installed without problem.

I used make deb for the compilation.

Sorry but I can't reproduce your problem

**Comment by ijpulidos** [comment]
I also cannot reproduce the issue, are you sure you are using the 4.82.00 branch?

**Comment by OleksandrPopovych** [comment]
I used master branch, instead 4.82.00 branch. And yes, now it's works with 4.82.00 branch, but I've added some little changes into setup.py: import numpy and add numpy.get_include() into include_dir list in order to prevent [numpy/arrayobject.h: No such file or directory] error

**Comment by ijpulidos** [comment]
What were the errors or what made you think you had to add these lines? So we can correct the setup.py if really needed.

**Comment by OleksandrPopovych** [comment]
I encountered with next error: numpy/arrayobject.h: No such file or directory
